### ISSUE TITLE
Subplots using choropleth() function

### ISSUE THREAD

**Issue by gdoshi2** [Wedg/PlotShapefiles.jl#2]
Hi, 
I had one more query regarding plotting using PlotShapefiles, so decided to create a separate issue. Is it possible to do something like a subplot using choropleth() function?

**Comment by Wedg** [comment]
Hi
Yes it is.

Something to bear in mind is that each of the plots of this package use the [Compose](https://github.com/GiovineItalia/Compose.jl) package. So you can use all the functionality of that package. (The exception is the Google map overlay which is an [Image](https://github.com/JuliaImages/Images.jl))

Here is a way to do the sub plots:
```julia
using Compose
plot1 = compose(context(), rectangle(), fill("red"))
plot2 = compose(context(), rectangle(), fill("blue"))
plot3 = compose(context(), rectangle(), fill("green"))
plot4 = compose(context(), rectangle(), fill("yellow"))
mainplot = compose(context(0.0, 0.0, 1.0, 1.0), (context(0.0, 0.0, 0.4, 0.4), plot1),
                                                (context(0.5, 0.0, 0.4, 0.4), plot2),
                                                (context(0.5, 0.5, 0.4, 0.4), plot3),
                                                (context(0.0, 0.5, 0.4, 0.4), plot4))
```
This produces:
![multicanvas](https://user-images.githubusercontent.com/8735697/39228042-3ed30fbe-485c-11e8-98d2-7719e829b303.PNG)

**Comment by gdoshi2** [comment]
Hi,
I tried this and it works! 
Thanks :-)
